In [2]:
import numpy as np
np.__version__

'1.26.1'

In [4]:
# macierz jednostkowa


In [7]:
np.eye(5, dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
# macierz odwrotna to tak sytuacja gdzie macierz A * B = B * A = I macierz jednostkowa

In [10]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [12]:
B = np.array([[2, 5], [6, -1]])
B

array([[ 2,  5],
       [ 6, -1]])

In [16]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [17]:
# Macierz transponowana zmienia kolumny na wiersze i wiersze na koluymny


In [18]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [19]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
price

array([[  12.4,   12.8,   11.9,   12.6, 1000. ],
       [  12.5,   13. ,   11.7,   12.2, 2000. ],
       [  12.2,   13.4,   12.2,   13.2, 1500. ]])