In [1]:
import numpy as np
np.__version__


'1.26.1'

In [5]:
x = np.array([[1,2], [1, 4]])
x

array([[1, 2],
       [1, 4]])

In [6]:
x.shape

(2, 2)

In [7]:
a = np.array([1, 2, 3])
a.dtype


dtype('int32')

In [8]:
a = np.array([1.2 , 2.3, 3.3])
a.dtype


dtype('float64')

In [9]:
a = np.array([1 , 2, 3], dtype = 'float')
a.dtype


dtype('float64')

In [10]:
print(a)

[1. 2. 3.]


In [11]:
#tworzenie tablic

In [23]:
a = np.zeros(shape = [3, 9], dtype = 'int')
a


array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
a = np.ones(shape = [3, 9], dtype = 'int')
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [29]:
a = np.full(shape = (3, 9), fill_value= 16, dtype = 'int')
a

array([[16, 16, 16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16, 16, 16]])

In [30]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(start= 4000, stop= 2000, step =-500)

array([4000, 3500, 3000, 2500])

In [35]:
np.linspace(start= 1, stop= 5, num= 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [36]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
# podstawowe operacje na tablicach


In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, -2, 3, 6])
print(a, b , sep = '\n')

[1 2 3 4]
[ 5 -2  3  6]


In [40]:
a + b

array([ 6,  0,  6, 10])

In [41]:
a - b

array([-4,  4,  0, -2])

In [42]:
np.add(a, b)

array([ 6,  0,  6, 10])

In [43]:
np.subtract(b, a)

array([ 4, -4,  0,  2])

In [44]:
# mnożenie
np.multiply(a, b)

array([ 5, -4,  9, 24])

In [45]:
# dzielenie
np.divide(a, b)

array([ 0.2       , -1.        ,  1.        ,  0.66666667])

In [46]:
# dzielenie
np.divide(b, a)

array([ 5. , -1. ,  1. ,  1.5])

In [51]:
x = np.array([[1, 5], [4, 6]])
y = np.array([[3, 7], [2, 9]])
print(x, '\n', y, sep = '\n')

[[1 5]
 [4 6]]


[[3 7]
 [2 9]]


In [53]:
# mnożenie matrixu
x_y = np.dot(x, y)
print(x_y)

[[13 52]
 [24 82]]


In [54]:
x_y = x.dot(y)
print(x_y)

[[13 52]
 [24 82]]


In [56]:
# mnożenie macierzy nie jest przemienne !!!


In [57]:
# mnożenie macierzy za pomocom funkcji @

x @ y

array([[13, 52],
       [24, 82]])

In [58]:
# GENEROWANIE LICZB PSEŁDO LOSOWYCH

In [61]:
np.random.seed(0)

In [62]:
np.random.randn()

1.764052345967664

In [63]:
np.random.randn(6)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842])

In [64]:
np.random.randn(14, 4)

array([[-0.15135721, -0.10321885,  0.4105985 ,  0.14404357],
       [ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628]])

In [65]:
np.random.rand()

0.06414749634878436

In [66]:
np.random.rand(10, 4)

array([[0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782],
       [0.39650574, 0.8811032 , 0.58127287, 0.88173536],
       [0.69253159, 0.72525428, 0.50132438, 0.95608363]])

In [67]:
np.random.randint(10)

1

In [68]:
np.random.randint(low=10, high= 200)

114

In [70]:
np.random.randint(low= 5, high= 100, size= 20)
# size - rozmiar generowanych danych 

array([29, 72, 87,  8, 81, 40, 91, 66, 74, 92, 48, 37, 16, 89, 15, 59, 42,
       33,  7, 32])

In [71]:
np.random.choice([2, 3, 5, 4, 3,]) # funkcja choice wybiera losowo liczbę z podanego przez nas zbioru 

4

In [72]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.random.shuffle(data) # fukcja shuffle tasuje nam nasza tablicę

In [74]:
data

array([0, 2, 1, 8, 6, 4, 3, 5, 7, 9])